#!/bin/sh -e
#
### BEGIN INIT INFO
# Provides: scribmanager
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: scribmanager
# Description: Internal Manager for S-CRIB Scramblers
### END INIT INFO

DAEMON="/home/scrib/scribManager.py"
DAEMONUSER="scrib"
DAEMON_NAME="scribManager.py"

PATH="/sbin:/bin:/usr/sbin:/usr/bin"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

d_start () {
        log_daemon_msg "Starting system $DAEMON_NAME Daemon"
        start-stop-daemon --name $DAEMON_NAME  --chuid $DAEMONUSER --chdir "/home/scrib" --start --exec $DAEMON -- > /dev/null 2>&1 &
        echo `/usr/bin/pgrep -o -f $DAEMON` > /var/run/$DAEMON_NAME.pid
        log_end_msg $?
}

d_stop () {
        log_daemon_msg "Stopping system $DAEMON_NAME Daemon"
        start-stop-daemon --name $DAEMON_NAME --stop --retry 5 --name $DAEMON_NAME
        rm -rf /var/run/$DAEMON.pid
        log_end_msg $?
}

case "$1" in

        start|stop)
                d_${1}
                ;;

        restart|reload|force-reload)
                        d_stop
                        d_start
                ;;

        force-stop)
               d_stop
                killall -q $DAEMON_NAME || true
                sleep 2
                killall -q -9 $DAEMON_NAME || true
                rm -rf /var/run/$DAEMON.pid
                ;;

        status)
                status_of_proc "$DAEMON" "$DAEMON_NAME" && exit 0 || exit $?
                ;;
        *)
                echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|force-stop|restart|reload|force-reload|status}"
                exit 1
                ;;
esac
exit 0
